configfile: "config/config.yaml"


pepfile: config["pepfile"]


# report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/local_data.smk"
include: "rules/trimming_filtering.smk"
include: "rules/analysis_reads.smk"
include: "rules/qualitycontrol.smk"


# include: "rules/assembly.smk"
# include: "rules/analysis.smk"
# include: "rules/assembly_qc.smk"


rule all:
    input:
        expand("results/{date}/report_prefilt/QC_all_prefilt.csv", date=get_run_date()),
        expand("results/{date}/report/QC_all_postfilt.csv", date=get_run_date()),
        expand(
            "results/{date}/analysis/resistance/{sample}/{sample}.allele_mapping_data.txt",
            date=get_run_date(),
            sample=get_samples(),
        ),
        expand(
            "results/{date}/analysis/plasmids/{sample}/{sample}_summary/{sample}_plasmid_summary.tsv",
            date=get_run_date(),
            sample=get_samples(),
        ),


"""        expand("results/{date}/report/multiqc.html", date=get_run_date()),
        expand("results/{date}/report_prefilt/multiqc.html", date=get_run_date()),
"""

"""     expand(
            "results/{date}/out/assembly/{sample}.fa.gz",
            date=get_run_date(),
            sample=get_samples(),
        ),
        expand(
            "results/{date}/report_prerequisites/assembly/{sample}_short_reads_mapped.txt",
            date=get_run_date(),
            sample=get_samples(),
        ),
        expand(
            "results/{date}/report_prerequisites/assembly/{sample}_long_reads_mapped.txt",
            date=get_run_date(),
            sample=get_samples(),
        ),
        expand(
            "results/{date}/qc/checkm2/{sample}/quality_report.tsv",
            date=get_run_date(),
            sample=get_samples(),
        ),
        expand(
            "results/{date}/analysis/plm_arg/{sample}/{sample}_arg.csv",
            date=get_run_date(),
            sample=get_samples(),
        ),
        expand(
            "results/{date}/qc/quast/{sample}/report.txt",
            date=get_run_date(),
            sample=get_samples(),
        ),
"""
