# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
pepfile: config/pep/config.yaml

# date of analysis or project name
run_date: "test_115"

data_handling:
  resources: "resources/"
  data:
    ont: "data/ont/"
    illumina: "data/illumina/"

adapter_seqs: "-a TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG -g GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG"

quality_criteria:
  illumina:
    min_quality: 20
    min_length: 15
  ont:
    min_quality: 15
    min_length: 500

checkm2_db:
  use_local: True
  local_path: "/groups/ds/databases_refGenomes/databases/latest/checkM2/checkm2_database.tar.gz"
  db_file: "CheckM2_database/uniref100.KO.1.dmnd"

plm_arg:
  git: "https://github.com/Junwu302/PLM-ARG.git"
  main: "PLM-ARG/plm_arg.py"
  model:
    use_local: True
    local_path: "/groups/ds/databases_refGenomes/databases/latest/PLM-ARG/model/esm1b_t33_650M_UR50S.pt"
    url: "https://dl.fbaipublicfiles.com/fair-esm/models/esm1b_t33_650M_UR50S.pt"
  regression:
    use_local: True
    local_path: "/groups/ds/databases_refGenomes/databases/latest/PLM-ARG/regression/esm1b_t33_650M_UR50S-contact-regression.pt"
    url: "https://dl.fbaipublicfiles.com/fair-esm/regression/esm1b_t33_650M_UR50S-contact-regression.pt"


#ill_data_path: "data/illumina/"

#"/projects/seqlab/GridIONs/20210713_JW001_KID1-3_Ec_ZKB_NBD104/20210713_JW001_KID1-3_Ec_ZKB_NBD104/20210713_1530_X2_FAP91220_d47f932e/sequencing_summary_FAP91220_e888cbe6.txt"
#summary_ont_run1: "data/ont/run1/sequencing_summary.txt"
#"/projects/seqlab/GridIONs/20211115_SM0006_JW0002_CefRes_strains_20211115/SM0006_JW0002_CefRes_strains_20211115/20211115_1648_X1_FAP91415_d0c3f758/sequencing_summary_FAP91415_f2d1671c.txt"
#summary_ont_run2: "data/ont/run2/sequencing_summary.txt"