# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
pepfile: config/pep/config.yaml

# date of analysis or project name
run_date: "test"

# choose between short, long or hybrid
assembly_type: "long"

data_handling:
  resources: "resources/"
  data:
    ont: "data/"
    illumina: "data/illumina/"

adapter_seqs: "-a TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG -g GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG"

quality_criteria:
  illumina:
    min_quality: 30
    min_length: 30
  ont:
    min_quality: 15
    min_length: 500

checkm2_db:
  use_local: True
  local_path: "/groups/ds/databases_refGenomes/databases/latest/checkM2/checkm2_database.tar.gz"
  db_file: "CheckM2_database/uniref100.KO.1.dmnd"

card:
  data:
    version: "v3.2.9"
    dbfile: "card.json"
    url: "https://card.mcmaster.ca/latest/data"

plm_arg:
  git: "https://github.com/Junwu302/PLM-ARG.git"
  main: "PLM-ARG/plm_arg.py"
  model:
    use_local: True
    local_path: "/groups/ds/databases_refGenomes/databases/latest/PLM-ARG/model/esm1b_t33_650M_UR50S.pt"
    url: "https://dl.fbaipublicfiles.com/fair-esm/models/esm1b_t33_650M_UR50S.pt"
  regression:
    use_local: True
    local_path: "/groups/ds/databases_refGenomes/databases/latest/PLM-ARG/regression/esm1b_t33_650M_UR50S-contact-regression.pt"
    url: "https://dl.fbaipublicfiles.com/fair-esm/regression/esm1b_t33_650M_UR50S-contact-regression.pt"
