show_analysis_time: True

# order of report
module_order:
  - fastqc:
      name: "Short Reads QC"
      target: "FastQC"
  - fastp:
      name: "Short Reads Preprocessing"
      target: "fastp"
  - nanostats:
      name: "Long Reads QC & Preprocessing"
      target: "nanostats"

report_section_order:
  fastqc_sequence_length_distribution: remove
  fastqc_per_sequence_gc_content: remove
  fastqc_per_base_n_content: remove
  fastqc_per_base_sequence_content: remove
  fastqc_sequence_duplication_levels: remove
  fastqc_per_base_sequence_quality: remove
  fastqc_status_checks:
    before: "fastqc_sequence_counts"

# sample name cleaning
fn_clean_exts:
  - ".fastp"
  - ".trimmed"
  - ".fastq"
  - ".gz"
  - "_R1"
  - "_R2"
  - ".1"
  - ".2"
  - "_NanoStats.txt"
  - "_NanoPlot-report.html"
  
# customising general Statistics
table_columns_visible:
  Reads Quality Control:
    percent_duplicates: False
    percent_gc: False
    avg_sequence_length: False
    percent_fails: False
    total_sequences: True
  Reads Preprocessing:
    pct_duplication: False
    after_filtering_q30_rate: False
    after_filtering_q30_bases: False
    after_filtering_gc_content: False
    pct_surviving: True
    pct_adapter: False